/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ArtistListRelationFilter } from "../../artist/base/ArtistListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { VenueWhereUniqueInput } from "../../venue/base/VenueWhereUniqueInput";
@InputType()
class EventWhereInput {
  @ApiProperty({
    required: false,
    type: () => ArtistListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ArtistListRelationFilter)
  @IsOptional()
  @Field(() => ArtistListRelationFilter, {
    nullable: true,
  })
  artists?: ArtistListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  date?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ArtistListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ArtistListRelationFilter)
  @IsOptional()
  @Field(() => ArtistListRelationFilter, {
    nullable: true,
  })
  eventsOpened?: ArtistListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => VenueWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VenueWhereUniqueInput)
  @IsOptional()
  @Field(() => VenueWhereUniqueInput, {
    nullable: true,
  })
  venue?: VenueWhereUniqueInput;
}
export { EventWhereInput };
